version: "3.2"

services:
  cnitch:
    image: quay.io/nicholasjackson/cnitch:latest
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - ${DOCKER_GROUP_ID}
    command: ["--hostname=localhost", "--statsd-server=statsd:9125"]

  dogstatsd:
    image: datadog/docker-dogstatsd:latest
    environment:
      - API_KEY=${DOG_API_KEY}
      - LOG_LEVEL=DEBUG
    user: ${DOG_GROUP_ID}

  statsd:
    image: prom/statsd-exporter

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 127.0.0.1:9090:9090
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000